### ISSUE TITLE
> Just noting that this added the jill.py rather than the original jill:

### ISSUE THREAD

**Issue by ngam** [conda-forge/jill-feedstock#3]
@mkitti, we can discuss here

> Just noting that this added the original jill rather jill.py:
> https://github.com/abelsiqueira/jill
> https://github.com/johnnychen94/jill.py

I can add the jillpy option through an output. Are they sufficiently different?

_Originally posted by @ngam in https://github.com/conda-forge/staged-recipes/issues/18240#issuecomment-1063107200_

**Comment by ngam** [comment]
We can use the trick of using the same feedstock for two different outputs here like I did here: https://github.com/conda-forge/coreutils-feedstock/pull/23

**Comment by mkitti** [comment]
Jill is written in shell ([ba]sh). Jill.py is written in Python.

**Comment by ngam** [comment]
Ah, we have the "improved" one. I think we can make do with jillpy then? Maybe I should rename it?

**Comment by mkitti** [comment]
Both are actively maintained. I suspect jill.py has greater utility to someone running Windows though. As far as I can understand, there is not a dependency between the two. jill.py is a complete rewrite.

**Comment by mkitti** [comment]
My suggestion would be to add a separate jillpy feedstock, but that's your call.

**Comment by ngam** [comment]
Just to be clear, we have jill.py here, not jill

**Comment by ngam** [comment]
Thing is, I have no idea what to make of a shell script here in conda-forge. We could simply just copy it and chmod it in $PREFIX/bin --- I guess that would be good enough, right? 

But then, we would have two `jill` commands in `bin/`; so we need to set a conflict between the two so that the user must choose one or the other (pretty easy to do like [this](https://github.com/conda-forge/singularityce-feedstock/blob/f358ec497f6a02029ab4bb5ecd9c2162bcbb512a/recipe/meta.yaml#L41-L44))

Overall, it seems like shell script is not necessarily designed to be a full-fledged program, and instead it is light-weight enough, one could just copy/wget it and run it...

**Comment by ngam** [comment]
I definitely want to correct my oversight of not noticing jill.sh and just running with jill.py as the `jill`

**Comment by mkitti** [comment]
Ah, I see I got it swapped now. jill.sh is quite light weight in terms of dependencies and thus much easier to install.



> But then, we would have two `jill` commands in `bin/`; so we need to set a conflict between the two so that the user must choose one or the other (pretty easy to do like [this](https://github.com/conda-forge/singularityce-feedstock/blob/f358ec497f6a02029ab4bb5ecd9c2162bcbb512a/recipe/meta.yaml#L41-L44))

Even if they were in the same bin directory, I think one would need to need explicitly execute jill.sh or jill.py, right? Does either of them run as just `jill` ?

**Comment by ngam** [comment]
> Does either of them run as just `jill` ?

Yep! Jill.py has an entry point as jill:

https://github.com/conda-forge/jill-feedstock/blob/5a265bb23693355a91a38a4f46ce8465e26b73a6/recipe/meta.yaml#L32-L41

**Comment by ngam** [comment]
https://github.com/conda-forge/jill-feedstock/blob/5a265bb23693355a91a38a4f46ce8465e26b73a6/recipe/meta.yaml#L12-L17

**Comment by ngam** [comment]
I think for now having jillpy only is the way to go. This is after all a primarily python ecosystem ... Closing for now, but we will revisit at some point later.

**Comment by mkitti** [comment]
> This is after all a primarily python ecosystem

Is it? It is a de facto python primarily ecosystem, but I get the impression it intends to be more. Anyways, this is fine with me.

Do you intend to bring the activation script here as well?

**Comment by ngam** [comment]
> Do you intend to bring the activation script here as well?

Ah, that's a good point! Let me think... 

> but I get the impression it intends to be more

I don't think there's any inherent intention honestly. It is just a super flexible system run by volunteers, so you can build anything you wish. But there is not like a set of instructions to expand into each corner of software... at least, not that I am aware of. 

I am reopening this to think about the scripts, thanks for bringing that up!

**Comment by ngam** [comment]
Btw, how do you feel about me adding you as a maintainer here and in the other feedstocks? No pressure, but since you're the one with vastly more julia experience, you may want to experiment and push things however you want — I generally prefer to defer to you :)

I would love to have you as a maintainer, but of course, you have to consent to be added first!

**Comment by mkitti** [comment]
Sure. Why not?

**Comment by ngam** [comment]
Let's refocus this convo on the scripts vis-a-vis windows: xref https://github.com/conda-forge/julia-feedstock/issues/194

would you want to make a ghost package for windows in julia-feedstock that can just use jill to download julia or do you prefer to just do that here? I am going to try to see if we could have an opt in type of thing and we need to condition on the scripts on certain versions (e.g. the stacking)

**Comment by mkitti** [comment]
You would know better than I what would match conda user expectations. If the label for the ghost package were clear, I think that would make sense. I feel like we need to write down documentation on this somewhere. Perhaps writing this up on https://discourse.julialang.org/ would make sense?

**Comment by ngam** [comment]
I think I would like to experiment with the following solution for Windows:
- create a split here
- one output is the same as now
- second output (name it `jill-conda-julia` or something like that) contains the scripts we have + instructions to automatically install julia from upstream (i.e. user will get the binaries from julia upstream automatically, but we won't ship them)

How does that sound to you? 

We will want to ensure a few things for completion:
- direct jill to install binaries in CONDA_REFIX
- carefully test the scripts
- before actually releasing this to main, we will want to consult with core/isuruf (at first we can release it in a separate dev channel)

**Comment by mkitti** [comment]
sounds good to me

**Comment by ngam** [comment]
may revisit later
